# Generated by Django 5.0.6 on 2024-09-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_products_category_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='food_images/thumbnail/'),
        ),
    ]
