# Generated by Django 5.0.6 on 2024-09-09 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_foodimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='foodimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
    ]
