# Generated by Django 5.0.6 on 2024-09-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_category_code_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='uploaded_at',
        ),
    ]
