# Generated by Django 5.0.6 on 2024-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 00011100011', max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
