# Generated by Django 5.0.6 on 2024-07-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is client?'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_waiter',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is waiter?'),
        ),
    ]
