# Generated by Django 5.0.6 on 2024-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_is_client_customuser_is_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='n', max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
