# Generated by Django 5.0.6 on 2024-09-09 01:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_cpf_remove_customuser_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Code'),
        ),
    ]
